chore: in theory a working publish pipeline

diff --git a/.github/workflows/publish-java.yaml b/.github/workflows/publish-java.yaml
--- a/.github/workflows/publish-java.yaml
+++ b/.github/workflows/publish-java.yaml
@@ -40,24 +40,41 @@ jobs:
         run: |
           echo "platform=${{ matrix.platform }}" >> $GITHUB_ENV
 
-      - name: Download Binary
+      - name: Set up Binary List
         run: |
-          BINARY_URL="https://github.com/${{ github.repository }}/releases/download/unleash-yggdrasil-v${CORE_VERSION}/${{ matrix.binary }}"
-          TARGET_DIR="java-engine/src/main/resources/native"
+          # List of binaries we want to download
+          binaries=(
+            "libyggdrasilffi_x86_64.so"
+            "libyggdrasilffi_arm64.so"
+            "libyggdrasilffi_x86_64-musl.so"
+            "libyggdrasilffi_arm64-musl.so"
+            "yggdrasilffi_x86_64.dll"
+            "yggdrasilffi_arm64.dll"
+            "libyggdrasilffi_x86_64.dylib"
+            "libyggdrasilffi_arm64.dylib"
+          )
+          echo "binaries=${binaries[@]}" >> $GITHUB_ENV
 
-          mkdir -p "$TARGET_DIR"
-          curl -L -o "$TARGET_DIR/${{ matrix.binary }}" \
-            -H "Authorization: token $GITHUB_TOKEN" \
-            "$BINARY_URL"
-
-          if [ -f "$TARGET_DIR/${{ matrix.binary }}" ]; then
-            echo "${{ matrix.binary }} downloaded successfully to $TARGET_DIR."
-          else
-            echo "Error: ${{ matrix.binary }} could not be downloaded."
-            exit 1
-          fi
+      - name: Download All Binaries
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          TARGET_DIR="java-engine/binaries"
+          mkdir -p "$TARGET_DIR"
+
+          for binary in ${binaries[@]}; do
+            echo "Downloading $binary..."
+            curl -L -o "$TARGET_DIR/$binary" \
+              -H "Authorization: token $GITHUB_TOKEN" \
+              "https://github.com/${{ github.repository }}/releases/download/unleash-yggdrasil-v${CORE_VERSION}/$binary"
+
+            if [ -f "$TARGET_DIR/$binary" ]; then
+              echo "$binary downloaded successfully."
+            else
+              echo "Error: $binary could not be downloaded."
+              exit 1
+            fi
+          done
 
       - name: Publish to Sonatype
         env:
@@ -67,4 +84,4 @@ jobs:
           ORG_GRADLE_PROJECT_signingPassphrase: ${{ secrets.GPG_PASSPHRASE }}
         run: |
           cd java-engine
-          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository -Pplatform=${{ matrix.platform }}
+          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
