chore: test ci wheel build

diff --git a/.github/workflows/publish-python.yml b/.github/workflows/publish-python.yml
--- a/.github/workflows/publish-python.yml
+++ b/.github/workflows/publish-python.yml
@@ -9,8 +9,7 @@ jobs:
     strategy:
       matrix:
         include:
-          - binary: libyggdrasilffi_x86_64.so
-            platform: x86_64-linux
+          - python-version: 3.10
 
     steps:
       - name: Checkout code
@@ -19,7 +18,7 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
-          python-version: "3.x"
+          python-version: ${{ matrix.python-version }}
 
       - name: Install Poetry
         run: |
@@ -32,26 +31,45 @@ jobs:
           echo "FFI Library Version: $CORE_VERSION"
           echo "CORE_VERSION=$CORE_VERSION" >> $GITHUB_ENV
 
-      - name: Download Binary
+      - name: Set up Binary List
+        run: |
+          # List of binaries we want to download
+          binaries=(
+            "libyggdrasilffi_x86_64.so"
+            "libyggdrasilffi_arm64.so"
+            "libyggdrasilffi_x86_64-musl.so"
+            "libyggdrasilffi_arm64-musl.so"
+            "yggdrasilffi_x86_64.dll"
+            "yggdrasilffi_arm64.dll"
+            "libyggdrasilffi_x86_64.dylib"
+            "libyggdrasilffi_arm64.dylib"
+          )
+          echo "binaries=${binaries[@]}" >> $GITHUB_ENV
+
+      - name: Download All Binaries
         run: |
 
-          BINARY_URL="https://github.com/${{ github.repository }}/releases/download/unleash-yggdrasil-v${CORE_VERSION}/${{ matrix.binary }}"
-          TARGET_DIR="python-engine/yggdrasil_engine/lib"
-
+          TARGET_DIR="python-engine/binaries"
           mkdir -p "$TARGET_DIR"
-          curl -L -o "$TARGET_DIR/${{ matrix.artifact_name }}" \
-            -H "Authorization: token $GITHUB_TOKEN" \
-            "$BINARY_URL"
 
-          if [ -f "$TARGET_DIR/${{ matrix.binary }}" ]; then
-            echo "${{ matrix.binary }} downloaded successfully to $TARGET_DIR."
-          else
-            echo "Error: ${{ matrix.binary }} could not be downloaded."
-            exit 1
-          fi
+          for binary in ${binaries[@]}; do
+            echo "Downloading $binary..."
+            curl -L -o "$TARGET_DIR/$binary" \
+              -H "Authorization: token $GITHUB_TOKEN" \
+              "https://github.com/${{ github.repository }}/releases/download/unleash-yggdrasil-v${CORE_VERSION}/$binary"
+
+            if [ -f "$TARGET_DIR/$binary" ]; then
+              echo "$binary downloaded successfully."
+            else
+              echo "Error: $binary could not be downloaded."
+              exit 1
+            fi
+          done
+
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Build wheel
+      - name: Build wheels
         run: |
-          poetry build
+          poetry install
+          tox
