chore: spike pipeline

diff --git a/.github/workflows/publish-java.yaml b/.github/workflows/publish-java.yaml
--- a/.github/workflows/publish-java.yaml
+++ b/.github/workflows/publish-java.yaml
@@ -1,109 +1,70 @@
----
-name: Publish Java Engine
+name: Publish Java
 on:
-  push:
-    tags:
-      - "java-engine-*"
   workflow_dispatch:
 
 jobs:
+
   release-linux:
-    if: startsWith(github.ref, 'refs/tags/java-engine')
     runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Build Rust library for linux
-        run: |
-          cargo build --release
-      - name: Setup Java
-        uses: actions/setup-java@v3
-        with:
-          java-version: 21
-          cache: "gradle"
-          distribution: "temurin"
-      - name: Deploy release
-        uses: burrunan/gradle-cache-action@v1
-        env:
-          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
-          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
-          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
-          ORG_GRADLE_PROJECT_signingPassphrase: ${{ secrets.GPG_PASSPHRASE }}
-        with:
-          job-id: release-linux
-          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
-          build-root-directory: java-engine
+    strategy:
+      matrix:
+        include:
+          - binary: libyggdrasilffi_x86_64.so
+            platform: x86_64-linux
+          # - binary: libyggdrasilffi_arm64.so
+          #   platform: arm-linux
+          # - binary: libyggdrasilffi_x86_64-musl.so
+          #   platform: x86_64-linux-musl
+          # - binary: libyggdrasilffi_arm64-musl.so
+          #   platform: aarch64-linux-musl
+          # - binary: yggdrasilffi_x86_64.dll
+          #   platform: x64-mingw32
+          # - binary: yggdrasilffi_arm64.dll
+          #   platform: arm64-mingw32
+          # - binary: libyggdrasilffi_x86_64.dylib
+          #   platform: x86_64-darwin
+          # - binary: libyggdrasilffi_arm64.dylib
+          #   platform: arm64-darwin
 
-  release-windows:
-    if: startsWith(github.ref, 'refs/tags/java-engine')
-    runs-on: windows-latest
     steps:
       - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - uses: actions-rs/toolchain@v1
-        with:
-          toolchain: stable
-          profile: minimal
-          override: true
 
-      - name: Build Rust Library for Windows
+      - name: Extract Yggdrasil Core Version
         run: |
-          cd yggdrasilffi
-          cargo build --release --target x86_64-pc-windows-gnu
-        working-directory: ${{ github.workspace }}
-      - name: Setup Java
-        uses: actions/setup-java@v3
-        with:
-          java-version: 21
-          cache: "gradle"
-          distribution: "temurin"
+          cd java-engine
+          CORE_VERSION=$(grep -E '^yggdrasilCoreVersion=' gradle.properties | cut -d'=' -f2)
+          echo "FFI Library Version: $CORE_VERSION"
+          echo "CORE_VERSION=$CORE_VERSION" >> $GITHUB_ENV
 
-      - name: Deploy release
-        uses: burrunan/gradle-cache-action@v1
+      - name: Set Platform Property for Gradle
+        run: |
+          echo "platform=${{ matrix.platform }}" >> $GITHUB_ENV
+
+      - name: Download Binary
+        run: |
+          BINARY_URL="https://github.com/${{ github.repository }}/releases/download/unleash-yggdrasil-v${CORE_VERSION}/${{ matrix.binary }}"
+          TARGET_DIR="java-engine/src/main/resources/native"
+
+          mkdir -p "$TARGET_DIR"
+          curl -L -o "$TARGET_DIR/${{ matrix.binary }}" \
+            -H "Authorization: token $GITHUB_TOKEN" \
+            "$BINARY_URL"
+
+          if [ -f "$TARGET_DIR/${{ matrix.binary }}" ]; then
+            echo "${{ matrix.binary }} downloaded successfully to $TARGET_DIR."
+          else
+            echo "Error: ${{ matrix.binary }} could not be downloaded."
+            exit 1
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Publish to Sonatype
         env:
           ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
           ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
           ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
           ORG_GRADLE_PROJECT_signingPassphrase: ${{ secrets.GPG_PASSPHRASE }}
-        with:
-          job-id: release-linux
-          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
-          build-root-directory: java-engine
-
-  release-macos:
-    if: startsWith(github.ref, 'refs/tags/java-engine')
-    runs-on: macos-latest
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - uses: actions-rs/toolchain@v1
-        with:
-          toolchain: stable
-          profile: minimal
-          override: true
-      - name: Build Rust Library for macOS
         run: |
-          cd yggdrasilffi
-          cargo build --release --target x86_64-apple-darwin
-        working-directory: ${{ github.workspace }}
-      - name: Setup Java
-        uses: actions/setup-java@v3
-        with:
-          java-version: 21
-          cache: "gradle"
-          distribution: "temurin"
-      - name: Deploy release
-        uses: burrunan/gradle-cache-action@v1
-        env:
-          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
-          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
-          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
-          ORG_GRADLE_PROJECT_signingPassphrase: ${{ secrets.GPG_PASSPHRASE }}
-        with:
-          job-id: release-linux
-          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
-          build-root-directory: java-engine
+          cd java-engine
+          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
